# Generated by Django 5.0 on 2023-12-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation", name="stock", field=models.IntegerField(null=True),
        ),
    ]
