# Generated by Django 5.0 on 2023-12-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="color_code",
            field=models.CharField(max_length=255),
        ),
    ]
