# Generated by Django 5.0 on 2023-12-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_color_color_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="color_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
