# Generated by Django 5.0 on 2023-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_color_color_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="color_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
