# Generated by Django 5.0 on 2023-12-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_color_color_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="variation", name="color",),
        migrations.RemoveField(model_name="variation", name="size",),
    ]
