# Generated by Django 5.0 on 2023-12-30 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_variation_color_remove_variation_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.color"
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="size",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.size"
            ),
        ),
    ]
