# Generated by Django 5.0 on 2023-12-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_variation_color_variation_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation", old_name="quantity", new_name="stock",
        ),
    ]
