# Generated by Django 5.0 on 2023-12-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_variation_stock_variation_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="colors_available",
            field=models.ManyToManyField(
                related_name="available_sizes", to="store.color"
            ),
        ),
    ]
