# Generated by Django 5.0 on 2024-01-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0003_remove_categoryoffer_category_and_more"),
        ("store", "0012_size_colors_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.categoryoffer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.productoffer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="referral_offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.referraloffer",
            ),
        ),
    ]
