# Generated by Django 5.0 on 2024-01-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product_category_offer_product_product_offer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="category_offer", new_name="offer",
        ),
        migrations.RemoveField(model_name="product", name="product_offer",),
        migrations.RemoveField(model_name="product", name="referral_offer",),
    ]
