# Generated by Django 5.0 on 2024-01-02 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_categoryoffer_is_available_productoffer_is_available_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="categoryoffer", name="category",),
        migrations.RemoveField(model_name="categoryoffer", name="discount_percentage",),
        migrations.RemoveField(model_name="productoffer", name="discount_percentage",),
        migrations.RemoveField(model_name="productoffer", name="product",),
        migrations.RemoveField(model_name="referraloffer", name="discount_percentage",),
        migrations.RemoveField(model_name="referraloffer", name="referrer",),
        migrations.AddField(
            model_name="categoryoffer",
            name="discount_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryoffer",
            name="offer_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productoffer",
            name="discount_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productoffer",
            name="offer_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="referraloffer",
            name="discount_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="referraloffer",
            name="offer_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="categoryoffer",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="categoryoffer",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="productoffer",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="productoffer",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
