# Generated by Django 5.0 on 2024-01-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0003_remove_categoryoffer_category_and_more"),
        ("store", "0014_rename_category_offer_product_offer_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="CategoryOffer", new_name="Offer",),
        migrations.DeleteModel(name="ProductOffer",),
        migrations.DeleteModel(name="ReferralOffer",),
    ]
