# Generated by Django 5.0 on 2023-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_saved_address",
            field=models.BooleanField(default=False),
        ),
    ]
