# Generated by Django 5.0 on 2023-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_address_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_saved_address",
            field=models.BooleanField(default=False),
        ),
    ]
