# Generated by Django 5.0 on 2023-12-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_address"),
    ]

    operations = [
        migrations.DeleteModel(name="Address",),
    ]
