# Generated by Django 5.0 on 2023-12-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_address_is_saved_address"),
        ("orders", "0004_alter_orderproduct_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.address",
            ),
        ),
    ]
