# Generated by Django 5.0 on 2023-12-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_address_is_saved_address"),
        ("orders", "0005_order_billing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="selected_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_orders",
                to="accounts.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_orders",
                to="accounts.address",
            ),
        ),
    ]
