# Generated by Django 5.0 on 2023-12-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_returneditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
