# Generated by Django 5.0 on 2023-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_notification_user_alter_notification_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
